2018-06-17 22:09:37,266 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:17:40,737 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:24:23,918 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:24:28,069 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,102 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,121 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,124 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,124 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,124 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,125 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,125 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,131 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:24:28,170 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:25:59,621 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:25:59,648 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:27:28,183 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:27:37,973 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:27:37,996 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:38:09,387 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:38:15,444 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:38:15,469 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:40:58,299 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:47:05,992 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:47:22,565 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:47:22,610 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:49:02,833 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:50:37,025 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:52:38,657 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:52:47,905 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:52:48,016 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:52:48,081 ERROR: Exception on / [GET] [in /Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/patryan/Development/mygithub/flask-starter/app/main/routes.py", line 15, in index
    return render_template('main/index.html', server_message="Flask, Jinja and Creative Tim.. working together!")
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patryan/Development/mygithub/flask-starter/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/patryan/Development/mygithub/flask-starter/app/templates/paper-dashboard-2/main/index.html", line 1, in top-level template code
    {% extends 'app_base.html' %}
  File "/Users/patryan/Development/mygithub/flask-starter/app/templates/paper-dashboard-2/app_base.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/patryan/Development/mygithub/flask-starter/app/templates/paper-dashboard-2/base.html", line 27, in top-level template code
    {% block body_content %}
  File "/Users/patryan/Development/mygithub/flask-starter/app/templates/paper-dashboard-2/app_base.html", line 75, in block "body_content"
    {% block main_content %}
  File "/Users/patryan/Development/mygithub/flask-starter/app/templates/paper-dashboard-2/main/index.html", line 279, in block "main_content"
    {% block scripts %}
  File "/Users/patryan/Development/mygithub/flask-starter/app/templates/paper-dashboard-2/main/index.html", line 280, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2018-07-03 18:52:48,092 ERROR: server error [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:14]
2018-07-03 18:54:00,031 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:54:04,414 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:54:08,280 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:54:08,280 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:29,593 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:57]
2018-07-03 18:55:30,727 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:36,563 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:55:36,564 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:39,028 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:55:39,028 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:41,076 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:8]
2018-07-03 18:55:41,076 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:43,261 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:43,322 INFO: User: <app.models.User object at 0x103c8c278> [in /Users/patryan/Development/mygithub/flask-starter/app/user_profile/routes.py:13]
2018-07-03 18:55:43,323 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:47,010 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:49,349 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:16]
2018-07-03 18:55:49,403 INFO: User: <app.models.User object at 0x103c8c1d0> [in /Users/patryan/Development/mygithub/flask-starter/app/user_profile/routes.py:13]
