2018-04-28 13:35:08,112 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-28 13:35:22,038 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:35:22,149 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:35:22,223 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:35:22,224 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:35:22,284 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:35:22,284 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:35:22,362 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:35:22,362 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:36:38,421 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-28 13:36:39,908 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:36:46,265 INFO: load_user: user [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:36:57,459 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:36:57,569 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:01,668 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:01,738 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:37:01,739 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:01,810 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:37:01,811 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:01,872 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:37:01,872 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:38,837 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:38,905 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:37:38,905 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:38,978 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:37:38,978 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:39,045 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-28 13:37:39,045 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:41,854 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-28 13:37:43,550 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:49,726 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:49,834 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:51,795 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:54,609 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-28 13:37:56,780 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-29 07:41:58,559 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-29 07:42:02,025 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-04-29 21:33:32,852 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-29 21:33:52,228 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-29 21:33:52,348 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-29 21:33:54,588 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:10:06,792 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-30 20:10:22,118 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:10:22,243 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:10:28,105 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:10:46,546 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:10:48,566 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:15:20,921 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-04-30 20:15:30,373 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-04-30 20:15:35,441 INFO: load_user: user1 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:06:36,753 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-05-02 14:06:55,585 INFO: load_user: user2 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:06:55,714 INFO: load_user: user2 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:06:58,485 INFO: load_user: user2 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:07:04,583 INFO: load_user: user2 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:07:10,853 INFO: load_user: user2 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:07:20,377 INFO: load_user: user2 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:05,906 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-05-02 14:08:08,082 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-05-02 14:08:18,510 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-05-02 14:08:45,518 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:45,640 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:45,737 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-05-02 14:08:45,738 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:47,652 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:47,733 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-05-02 14:08:47,734 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:54,684 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:08:54,774 ERROR: File not found [in /Users/patryan/Development/mygithub/flask-starter/app/errors/handlers.py:7]
2018-05-02 14:17:32,667 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-05-02 14:17:44,726 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:17:44,847 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-02 14:17:49,747 INFO: load_user: user3 [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:12]
2018-05-07 19:49:48,533 INFO: Flask Starter startup [in /Users/patryan/Development/mygithub/flask-starter/app/__init__.py:44]
2018-05-07 19:50:14,275 INFO: load_user: admin [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:13]
2018-05-07 19:50:14,390 INFO: load_user: admin [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:13]
2018-05-07 19:50:26,352 INFO: load_user: admin [in /Users/patryan/Development/mygithub/flask-starter/app/services/auth_services.py:13]
